---
slurm_packages:
  - slurmctld
  - slurmdbd

slurm_elastic:
  oracle:
    config_directory: /home/slurm/.oci/

install_packages:
  - xorg-x11-xauth
  - cuda
  - cuda-cudart-9-1
  - cuda-cufft-9-1

monitoring_role: master
