---
- name: common
  hosts: all
  tags: common
  roles:
    - dhcp
    - epel
    - security-updates
    - debug-tools
    - ntp
    - filesystem
    - users
- import_playbook: management.yml
- import_playbook: compute.yml
