---
- name: common
  hosts: all
  tags: common
  roles:
    - dhcp
    - ssh
    - epel
    - security-updates
    - ntp
    - filesystem
    - users
    - monitoring
- import_playbook: management.yml
- import_playbook: compute.yml
- name: finalise
  hosts: all
  tags: finalise
  roles:
    - finalise
