---
- name: checkout Ansible repo
  git:
    repo: https://github.com/ACRC/slurm-ansible-playbook.git
    dest: /home/opc/slurm-ansible-playbook
- name: copy example users file
  copy:
    src: users.yml.example
    dest: /home/opc/users.yml.example
- name: copy over finisher script
  copy:
    src: finish.py
    dest: /home/opc/finish
    mode: 0755
- file:
    path: /mnt/shared/finalised
    state: directory
    mode: 0755
- file:
    path: /mnt/shared/finalised/{{ansible_hostname}}
    state: touch
    mode: 0777
