---
- name: install munge
  yum:
    name: munge
    state: installed

- name: copy in munge key
  copy:
    src: munge.key
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: 0400

- name: start service munge
  service:
    name: munge
    enabled: yes
    state: started

- name: install Slurm build dependencies
  yum:
    name:
      - gcc
      - make
      - rpm-build
      - munge-devel
      - readline-devel
      - openssl-devel
      - pam-devel
      - gtk2-devel
      - mariadb-devel
      - perl-ExtUtils-MakeMaker
    state: present

- name: download Slurm source
  get_url:
    url: https://download.schedmd.com/slurm/slurm-{{ slurm_version }}.tar.bz2
    dest: /tmp/
    checksum: "{{ slurm_download_checksum }}"
  register: download_slurm_source

- name: rpmbuild Slurm
  command: rpmbuild -ta {{ download_slurm_source.dest }}
  args:
    chdir: /tmp
    creates: /root/rpmbuild/RPMS/x86_64/slurm-{{ slurm_version }}-1.el7.x86_64.rpm

- name: install Slurm base package
  yum: name=/root/rpmbuild/RPMS/x86_64/slurm-{{ slurm_version }}-1.el7.x86_64.rpm state=present

- name: install Slurm
  yum: name=/root/rpmbuild/RPMS/x86_64/slurm-{{item}}-{{ slurm_version }}-1.el7.x86_64.rpm state=present
  loop: "{{ slurm_packages }}"

- file:
    path: /etc/slurm
    state: directory
    mode: 0755

- name: create slurm group
  group:
    name: slurm
    state: present

- name: create slurm user
  user:
    name: slurm
    comment: Slurm controller user
    group: slurm

- name: slurm config file
  template:
    src: slurm.conf.j2
    dest: /etc/slurm/slurm.conf
    owner: slurm
    group: slurm
    mode: 0644
  notify: restart slurmctld

- name: slurmdbd config file
  template:
    src: slurmdbd.conf.j2
    dest: /etc/slurm/slurmdbd.conf
    owner: slurm
    group: slurm
    mode: 0400
  notify:
    - restart slurmctld
    - restart slurmdbd

- name: cgroup config file
  template:
    src: cgroup.conf.j2
    dest: /etc/slurm/cgroup.conf
    owner: slurm
    group: slurm
    mode: 0400
  notify:
    - restart slurmd
    - restart slurmctld

- file:
    path: /var/log/slurm/
    state: directory
    owner: slurm
    group: slurm
    mode: 0755

- file:
    path: /var/spool/slurm/
    state: directory
    owner: slurm
    group: slurm
    mode: 0755

- file:
    path: /var/spool/slurmd/
    state: directory
    owner: slurm
    group: slurm
    mode: 0755

- name: open firewall for slurm
  firewalld:
    port: 6817-6818/tcp
    permanent: true
    state: enabled
  notify:
    - restart firewalld
    - restart slurmctld
    - restart slurmd

- include_tasks: elastic.yml
  when: "'management' in group_names"

- name: start service slurmdbd
  service:
    name: slurmdbd
    state: started
    enabled: yes
  when: "'management' in group_names"

- name: start service slurmctld
  service:
    name: slurmctld
    state: started
    enabled: yes
  when: "'management' in group_names"

- name: start service slurmd
  service:
    name: slurmd
    state: started
    enabled: yes
  when: "'management' not in group_names"

- name: create accounting cluster
  command: sacctmgr --immediate add cluster {{ slurm_cluster_name }}
  register: create_cluster_result
  changed_when: "create_cluster_result.rc == 0"
  failed_when: "create_cluster_result.rc != 0 and create_cluster_result.stdout != ' This cluster {{ slurm_cluster_name }} already exists.  Not adding.'"
  when: "'management' in group_names"
