---
#
# This is the one file that violates my rule of "don't just throw a bunch of
# stuff into a role." These are all really useful tools, with single line
# installs
#

- name: yum install useful tools
  package:
    name:
      - curl
      - htop
      - iotop
      - lsof
      - rsync
      - screen
      - sysstat
      - tcpdump
      - traceroute
      - wget
      - nmap
      - git
      - cmake

- name: enable CUDA repo
  yum_repository:
    name: nvidia
    description: NVIDIA CUDA
    baseurl: http://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64
    gpgkey: http://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/7fa2af80.pub

- name: yum install packages
  yum:
    name: "{{ install_packages }}"
